### ISSUE TITLE
Add option for zero-terminated string

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [Cysharp/Utf8StringInterpolation#18]
First of all, thank you for the fantastic library! The idea and the performance are great.

I'm having an issue when utilizing this library to generate UTF8 strings that are consumed by native C methods expecting a zero-terminated string. `Utf8StringWriter` doesn't add a zero terminator to the end, and there's no place to add it manually when using `Utf8StringWriter` as a function argument. 

Here's an example of the code I'm trying to achieve. 
```csharp
private static unsafe void ProcessData(
    ref Utf8StringWriter<ArrayBufferWriter<byte>> label, 
    ref Utf8StringWriter<ArrayBufferWriter<byte>> data
) {
    label.Flush();
    ReadOnlySpan<byte> labelSpan = label.GetBufferWriter().WrittenSpan;
    
    data.Flush();
    ReadOnlySpan<byte> dataSpan = data.GetBufferWriter().WrittenSpan;

    fixed (byte* labelBytes = &labelSpan.GetPinnableReference())
        fixed (byte* dataBytes = &dataSpan.GetPinnableReference())
            NativeMethods.ProcessData(labelBytes, dataBytes);
}
```

**Comment by neuecc** [comment]
`AppendUtf8` means writer war bytes.
So you can write like this.

```csharp
label.AppendUtf8([0]);
label.Flush();
```

**Comment by neuecc** [comment]
The size of Utf8StringWriter is not exact.
`var initialSize = literalLength + (formattedCount * GuessedLengthPerHole);`
The length used for Hole is unknown, so it's just an estimate.
It might be larger or smaller.
Therefore, practically speaking, there's likely no difference in adding 1.
So we can consider that there are no performance concerns.
