### ISSUE TITLE
Strings are corrupted when multiple Utf8StringWriter<ArrayBufferWriter<byte>> are used in method declaration

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [Cysharp/Utf8StringInterpolation#19]
If there's more than one `Utf8StringWriter<ArrayBufferWriter<byte>>` argument in method declaration, the string data gets corrupted.

Example method declaration:

```csharp
private static void ProcessData(
    ref Utf8StringWriter<ArrayBufferWriter<byte>> label, 
    ref Utf8StringWriter<ArrayBufferWriter<byte>> data
) 
{ ... }
```

Looking at the implementation, this happens because whenever Utf8StringWriter<ArrayBufferWriter<byte>> is used as a function argument, its constructor calls `ArrayBufferWriterPool.GetThreadStaticInstance()`, which resets the state of `ArrayBufferWriter`. So the first argument get processed, then, the second `Utf8StringWriter` gets created for the second argument, resetting the `ArrayBufferWriter` state, and now, the first `Utf8StringWriter` is in a corrupted state - it's data is being overwritten by the second `Utf8StringWriter`.

**Comment by neuecc** [comment]
Indeed.
ThreadStatic used to do well with the Serializer's static method, but it's a design that doesn't fit in Utf8StringWriter.
I would like to fix this.

**Comment by neuecc** [comment]
This is an early design flaw, but we didn't really expect external users to use this class.
We need to change the design to make Dispose mandatory (I believe Dispose itself is already supported, but it's not even being used within the library!).
 At this point, the extent of the changes might be too significant and difficult to implement.
